### ISSUE TITLE
shared links

### ISSUE THREAD

**Issue by gsjv2** [datrh/LibreELEC.tv#24]
Hi Datrh,

Since minixforum has been offline for months.  Are you posting the compiled updates anywhere else?  I've been just compiling on my own, but my build machine died.

Thanks!

-Grint

**Comment by datrh** [comment]
https://forum.libreelec.tv/thread/12155-libreelec-8-90-x-kodi-18-for-minix-x8-x8h-x8hplus-mx3-g-plus-and-s905-x-d-w/

ur welcome
